version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nest-api-database
    restart: no
    environment:
      POSTGRES_USER: nest-user
      POSTGRES_PASSWORD: nest-pass
      POSTGRES_DB: nest-db
    expose: [5432]
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nestjs-api-network

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    env_file: ./.env
    networks:
      - nestjs-api-network

volumes:
  pgdata:

networks:
  nestjs-api-network:
    name: nestjs-api-network
    driver: bridge