version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nest-api-database
    restart: no
    environment:
      POSTGRES_USER: nest-user
      POSTGRES_PASSWORD: nest-pass
      POSTGRES_DB: nest-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: